# Generated by Django 2.2.5 on 2020-02-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_superhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
