# Generated by Django 2.2.5 on 2020-03-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200229_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenties',
            new_name='amenities',
        ),
    ]
